services:
  - type: web
    name: printababes-laravel
    env: php
    plan: free
    buildCommand: |
        cp .env.example .env
        composer install --no-dev --optimize-autoloader
        php artisan key:generate --force
        php artisan migrate --force
        php artisan storage:link
        npm install
        npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://printababes.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
